branch-defaults:
  master:
    environment: production
  putCartOnHold:
    environment: null
environment-defaults: null
global:
  application_name: ferreteriaReact
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Ruby
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
production:
  branch: null
  repository: null
