branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: ferreteriaReact
  branch: master
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.6 (Passenger Standalone)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application
